name: scantron
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0
  firebase_analytics: ^9.3.6
  firebase_storage: ^10.3.9
  cloud_functions: ^3.3.8
  firebase_core: ^1.23.0
  flutterfire_ui: ^0.4.3+10
  firebase_messaging: ^13.0.3
  provider: ^6.0.3
  file_picker: ^5.2.0+1
  collection: ^1.16.0
  rxdart: ^0.27.5
  flutter_markdown: ^0.6.12
  expandable: ^5.0.1
  markdown: ^6.0.1
  url_launcher: ^6.1.5
  sentry_flutter: ^6.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: []
  fonts: []
